#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V

bspc config border_width         3
bspc config focused_border_color \#ffffff
bspc config normal_border_color \#dbd1be
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc config focus_follows_pointer true
#bspc config gapless_monocle true
#bspc config paddingless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# The AlvinPix edits

nitrogen --restore &
lxappearance &
${HOME}/.config/polybar/launch.sh --cuts $
xsetroot -cursor_name left_ptr &
#picom &
#compton &
